FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
        websockify \
        openssl && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY websockify-startup.sh /startup.sh

ENV  VNC_SERVER_HOST=localhost
ENV  VNC_SERVER_PORT=5901
ENV  WEBSOCKIFY_PORT=5902

CMD [ "/startup.sh" ]